name: Deploy FractionEHR Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Prepare website
        run: |
          mkdir -p site/assets/png
          mkdir -p site/assets/svg

          cp -r fractionehrartifact/. site/

          find fractionehrartifact -maxdepth 1 -type f -name "*.png" -exec cp {} site/assets/png/ \;
          find fractionehrartifact -maxdepth 1 -type f -name "*.svg" -exec cp {} site/assets/svg/ \;

          cp fractionehrartifact/index_local.html site/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
